# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Colony < Formula
  desc ""
  homepage "https://github.com/konstructio/colony"
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/konstructio/colony/releases/download/v0.0.2/colony_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy 
      sha256 "7b39dd184e871239ab7a1327c27dc3fdef820c2fc988d1bddee3c9c81628d113"

      def install
        bin.install "colony"
      end
    end
    on_arm do
      url "https://github.com/konstructio/colony/releases/download/v0.0.2/colony_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy 
      sha256 "442fe95f6f74dddf230558e38af5f5169ed5196403d5bb87a024ab2cdfdd1271"

      def install
        bin.install "colony"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/colony/releases/download/v0.0.2/colony_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy 
        sha256 "18da8d45f5dc9b38c91f36341021aaaabd59af74ea5ae78a32bfbb1a685053e7"

        def install
          bin.install "colony"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/colony/releases/download/v0.0.2/colony_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy 
        sha256 "ed48d1ed81422f845c5a5394e3439a3e991768d599245ee96f2c6e7b05ac44cf"

        def install
          bin.install "colony"
        end
      end
    end
  end
end
