# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Colony < Formula
  desc ""
  homepage "https://github.com/konstructio/colony"
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/konstructio/colony/releases/download/v0.0.4/colony_Darwin_x86_64.tar.gz"
      sha256 "7a9e6be94ca06c6bcc13582c325937a8e5e18aa8dc7377126ad4ab4aeba7caca"

      def install
        bin.install "colony"
      end
    end
    on_arm do
      url "https://github.com/konstructio/colony/releases/download/v0.0.4/colony_Darwin_arm64.tar.gz"
      sha256 "95065dee2cfc3de6e159c169d4dfe4e46393f458ed6b1ea11eae0addec9ba06c"

      def install
        bin.install "colony"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/colony/releases/download/v0.0.4/colony_Linux_x86_64.tar.gz"
        sha256 "5dfb42bde1c33c6a99ad1b753824759f1cf482d1b3662ee1ebf4dec5c6519ac6"

        def install
          bin.install "colony"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/colony/releases/download/v0.0.4/colony_Linux_arm64.tar.gz"
        sha256 "32ad515c4038998ef1b12c5ad5f5aa5447c843cc93d32325e6dc7a9a1e5cf00e"

        def install
          bin.install "colony"
        end
      end
    end
  end
end
