# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dropkick < Formula
  desc ""
  homepage "https://github.com/konstructio/dropkick"
  version "0.0.9"

  on_macos do
    on_intel do
      url "https://github.com/konstructio/dropkick/releases/download/v0.0.9/dropkick_Darwin_x86_64.tar.gz"
      sha256 "0bdb318789613bf5ca40b5c242a42bc31fd4c854ef2be200a176732ad4fd8519"

      def install
        bin.install "dropkick"
      end
    end
    on_arm do
      url "https://github.com/konstructio/dropkick/releases/download/v0.0.9/dropkick_Darwin_arm64.tar.gz"
      sha256 "d11d31dd519549b370d30bf8c2a8e6b530e08c280f8352cb9b7cb48d772ac9cb"

      def install
        bin.install "dropkick"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/dropkick/releases/download/v0.0.9/dropkick_Linux_x86_64.tar.gz"
        sha256 "4ba0601cf28e81defa94e84e6b40f6bff1f05de7a829861fc92dc583755ea751"

        def install
          bin.install "dropkick"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/dropkick/releases/download/v0.0.9/dropkick_Linux_arm64.tar.gz"
        sha256 "9b13712975d17cc9aeabac583970f0aa37cc1a27346037e828eac03c248fc0fb"

        def install
          bin.install "dropkick"
        end
      end
    end
  end
end
