# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HelmMirror < Formula
  desc ""
  homepage "https://github.com/konstructio/helm-mirror"
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/konstructio/helm-mirror/releases/download/v0.5.0/helm-mirror_darwin_x86_64.tar.gz"
      sha256 "0c5d048ebdca377b064bb6e20129a1bf407282adfd79e0d9507590908cb87bc4"

      def install
        bin.install "bin/mirror"
      end
    end
    on_arm do
      url "https://github.com/konstructio/helm-mirror/releases/download/v0.5.0/helm-mirror_darwin_arm64.tar.gz"
      sha256 "b319e452e2fa72f4a062de2638f68f30a9b2810a7ecea14dbc8f9247881786f4"

      def install
        bin.install "bin/mirror"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/helm-mirror/releases/download/v0.5.0/helm-mirror_linux_x86_64.tar.gz"
        sha256 "b8ed04f80ce98938130850b3279fb9f5f5956fb169e560c06f4e12cc428a0c40"

        def install
          bin.install "bin/mirror"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/helm-mirror/releases/download/v0.5.0/helm-mirror_linux_arm.tar.gz"
        sha256 "a17c085505b2e31f85569e9b1055606b98f35bad14867f28fa2b93f1d45c21fe"

        def install
          bin.install "bin/mirror"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/helm-mirror/releases/download/v0.5.0/helm-mirror_linux_arm64.tar.gz"
        sha256 "9124e120a850655a036b85194f1507884946dbc2142b6c645725f79df2e9b8dd"

        def install
          bin.install "bin/mirror"
        end
      end
    end
  end
end
