# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefirst < Formula
  desc ""
  homepage "https://github.com/konstructio/kubefirst"
  version "2.6.1"

  depends_on "aws-iam-authenticator"

  on_macos do
    on_intel do
      url "https://github.com/konstructio/kubefirst/releases/download/v2.6.1/kubefirst_2.6.1_darwin_amd64.tar.gz"
      sha256 "1ebaaaf65f667e0ac45ebe3150cb0665aad2133d9c2a47503572de497c1a5a48"

      def install
        bin.install "kubefirst"
      end
    end
    on_arm do
      url "https://github.com/konstructio/kubefirst/releases/download/v2.6.1/kubefirst_2.6.1_darwin_arm64.tar.gz"
      sha256 "f6f571cb4eaf75af2c3c71d62e2ce07515fe788ba709da24f7bd40e766c65fa9"

      def install
        bin.install "kubefirst"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/kubefirst/releases/download/v2.6.1/kubefirst_2.6.1_linux_amd64.tar.gz"
        sha256 "36c23e0fb81043e877499b8ca119494a50d760a2fbc988df5d034f7fd57b9a80"

        def install
          bin.install "kubefirst"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/konstructio/kubefirst/releases/download/v2.6.1/kubefirst_2.6.1_linux_arm64.tar.gz"
        sha256 "0fd69f0448d213163af67629cda85c1f570138945c1467630ae52adc4b2f5280"

        def install
          bin.install "kubefirst"
        end
      end
    end
  end
end
